apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uh4zuc60l-go 
  janus-idp.io/tekton: uh4zuc60l-go
  backstage.io/kubernetes-id: uh4zuc60l-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uh4zuc60l-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  